/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { AddDocumentDtoDocumentType } from './addDocumentDtoDocumentType';

export interface AddDocumentDto {
  documentType: AddDocumentDtoDocumentType;
  url: string;
  key?: string;
}
