/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type ApplicationDtoStage = typeof ApplicationDtoStage[keyof typeof ApplicationDtoStage];


export const ApplicationDtoStage = {
  SENT: 'SENT',
  NOT_SENT: 'NOT_SENT',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
} as const;
