/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { ApplicationDtoStage } from './applicationDtoStage';
import type { ConversationDto } from './conversationDto';
import type { Listing } from './listing';

export interface ApplicationDto {
  _id: string;
  listing: Listing;
  conversation: ConversationDto;
  landlord: string;
  applicants: string[];
  createdAt: string;
  owner: string;
  stage: ApplicationDtoStage;
}
