/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { MessageDto } from './messageDto';
import type { UserDto } from './userDto';

export interface ConversationDto {
  _id: string;
  name: string;
  lastMessage?: MessageDto;
  createdAt: string;
  groupDescription: string;
  avatar: string;
  users: UserDto[];
  messages: MessageDto[];
}
