/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type CreateListingDtoFurnishingStatus = typeof CreateListingDtoFurnishingStatus[keyof typeof CreateListingDtoFurnishingStatus];


export const CreateListingDtoFurnishingStatus = {
  Furnished: 'Furnished',
  Unfurnished: 'Unfurnished',
  'Part-Furnished': 'Part-Furnished',
} as const;
