/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type CreateFlagDtoCategory = typeof CreateFlagDtoCategory[keyof typeof CreateFlagDtoCategory];


export const CreateFlagDtoCategory = {
  INNAPPROPRIATE_BEHAVIOUR: 'INNAPPROPRIATE_BEHAVIOUR',
  OTHER: 'OTHER',
} as const;
