/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type DocumentTypesDtoDataItem = typeof DocumentTypesDtoDataItem[keyof typeof DocumentTypesDtoDataItem];


export const DocumentTypesDtoDataItem = {
  IDENTIFICATION: 'IDENTIFICATION',
  PROOF_OF_INCOME: 'PROOF_OF_INCOME',
  GUARANTOR_AGREEMENT: 'GUARANTOR_AGREEMENT',
  LANDLORD_REFERENCE: 'LANDLORD_REFERENCE',
  CHARACTER_REFERENCE: 'CHARACTER_REFERENCE',
} as const;
