/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { DocumentTypesDtoDataItem } from './documentTypesDtoDataItem';

export interface DocumentTypesDto {
  data: DocumentTypesDtoDataItem[];
}
