/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type FlagStatus = typeof FlagStatus[keyof typeof FlagStatus];


export const FlagStatus = {
  UNDER_REVIEW: 'UNDER_REVIEW',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  NO_ACTION: 'NO_ACTION',
} as const;
