/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { FlagCategory } from './flagCategory';
import type { FlagStatus } from './flagStatus';

export interface Flag {
  _id: string;
  status: FlagStatus;
  category: FlagCategory;
  reportedUser: string;
  createdBy: string;
  text: string;
  resolutionDate?: string;
}
