/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type FlagCategory = typeof FlagCategory[keyof typeof FlagCategory];


export const FlagCategory = {
  INNAPPROPRIATE_BEHAVIOUR: 'INNAPPROPRIATE_BEHAVIOUR',
  OTHER: 'OTHER',
} as const;
