/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { Listing } from './listing';

export interface LikedListingsDto {
  data: Listing[];
  total: number;
}
