/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { ListingsControllerGetFilteredListingsPropertyType } from './listingsControllerGetFilteredListingsPropertyType';

export type ListingsControllerGetFilteredListingsParams = {
propertyType: ListingsControllerGetFilteredListingsPropertyType;
numOfPeople: number;
monthlyRentMin: number;
monthlyRentMax: number;
sizeSqMeters: number;
amenities: string[];
lat: number;
lng: number;
};
