/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type MessageDtoMessageType = typeof MessageDtoMessageType[keyof typeof MessageDtoMessageType];


export const MessageDtoMessageType = {
  Text: 'Text',
  Image: 'Image',
} as const;
