/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { MessageDtoMessageType } from './messageDtoMessageType';
import type { UserDto } from './userDto';

export interface MessageDto {
  _id: string;
  sender: UserDto;
  messageType: MessageDtoMessageType;
  data: string;
  createdAt: string;
  conversation: string;
  seenUsers: string[];
  deliveredTo: string[];
}
