/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export interface PresignResDto {
  uploadUrl: string;
  fileUrl: string;
  key: string;
}
