/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */

export type UploadControllerGetPresignedUrlFolder = typeof UploadControllerGetPresignedUrlFolder[keyof typeof UploadControllerGetPresignedUrlFolder];


export const UploadControllerGetPresignedUrlFolder = {
  public: 'public',
  private: 'private',
} as const;
