/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { UploadControllerGetPresignedUrlFolder } from './uploadControllerGetPresignedUrlFolder';

export type UploadControllerGetPresignedUrlParams = {
fileType: string;
folder: UploadControllerGetPresignedUrlFolder;
filename: string;
};
