/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * My API
 * API documentation for my NestJS app
 * OpenAPI spec version: 1.0
 */
import type { UserDtoRole } from './userDtoRole';

export interface UserDto {
  _id: string;
  name: string;
  email: string;
  role: UserDtoRole;
  profilePicUrl: string;
  isVerified: string;
  lastSeen: string;
}
