// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type UserDto = {
    _id: string;
    name: string;
    email: string;
    role: 'SUPERUSER' | 'STUDENT' | 'LANDLORD_AGENCY';
    profilePicUrl: string;
    isVerified: string;
};

export type ErrorDto = {
    /**
     * HTTP status code
     */
    statusCode: number;
    /**
     * HTTP error message
     */
    message: string;
    /**
     * Error type
     */
    error?: string;
};

export type CreateUserDto = {
    name: string;
    email: string;
    role: string;
    imageUrl: string;
    password: string;
    emailVerificationToken: string;
    emailVerificationTokenExpires: string;
};

export type SetProfilePicDto = {
    url: string;
};

export type SetUsernameDto = {
    name: string;
};

export type LoginDto = {
    email: string;
    password: string;
};

export type VerifyEmailDto = {
    token: string;
    userId: string;
};

export type ForgotPasswordDto = {
    email: string;
};

export type ConfirmPasswordResetDto = {
    userId: string;
    token: string;
    newPassword: string;
};

export type Step4ItemDto = {
    name: string;
    desc: string;
    required: boolean;
};

export type CreateListingDto = {
    propertyTitle: string;
    numOfPeople: number;
    sizeSqMeters: number;
    propertyType: 'FLAT_APARTMENT' | 'HOUSE' | 'ROOM_IN_SHARED_HOUSE' | 'STUDIO' | 'OTHER';
    streetAddress: string;
    cityTown: string;
    postcodeZIP: string;
    country: string;
    bedroomsCount: number;
    enSuiteBedroomCount: number;
    bathrooms: number;
    propertyDesc: string;
    monthlyRent: number;
    securityDeposit: number;
    availableFrom: string;
    availableUntil: string;
    registerOfTitleKey: string;
    furnishingStatus: 'furnished' | 'unfurnished' | 'partFurnished';
    epcRating: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G';
    photos: Array<string>;
    videoTourLink: string;
    floorPlanImage: string;
    amenities: Array<string>;
    requirements: Array<Step4ItemDto>;
};

export type Listing = {
    _id: string;
    landlord: string;
    propertyTitle: string;
    numOfPeople: number;
    sizeSqMeters: number;
    propertyType: 'FLAT_APARTMENT' | 'HOUSE' | 'ROOM_IN_SHARED_HOUSE' | 'STUDIO' | 'OTHER';
    bedroomsCount: number;
    enSuiteBedroomCount: number;
    bathrooms: number;
    registerOfTitleKey: string;
    propertyDesc: string;
    amenities: Array<string>;
    streetAddress: string;
    cityTown: string;
    postcodeZIP: string;
    country: string;
    monthlyRent: number;
    securityDeposit: number;
    availableFrom: string;
    availableUntil: string;
    furnishingStatus: 'furnished' | 'unfurnished' | 'partFurnished';
    epcRating: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G';
    photos: Array<string>;
    videoTourLink: string;
    floorPlanImage: string;
    requirements: Array<string>;
    isVerified: boolean;
    isDraft: boolean;
    lastUpdated: string;
};

export type Step2ListingDto = {
    furnishingStatus: string;
    epcRating: string;
    amenities: Array<string>;
};

export type Step3ListingDto = {
    photos: Array<string>;
    videoTourLink: string;
    floorPlanImage: string;
};

export type Step4ListingDto = {
    requirements: Array<Step4ItemDto>;
};

export type MessageDto = {
    _id: string;
    sender: string;
    messageType: 'Text' | 'Image';
    data: string;
    createdAt: string;
    conversation: string;
    seenUsers: Array<string>;
    deliveredTo: Array<string>;
};

export type ConversationDto = {
    _id: string;
    name: string;
    createdAt: string;
    groupDescription: string;
    avatar: string;
    users: Array<string>;
    messages: Array<MessageDto>;
};

export type ContactDto = {
    [key: string]: unknown;
};

export type AppControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type AppControllerGetHelloResponses = {
    200: unknown;
};

export type UsersControllerGetUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersControllerGetUserErrors = {
    401: ErrorDto;
    404: ErrorDto;
};

export type UsersControllerGetUserError = UsersControllerGetUserErrors[keyof UsersControllerGetUserErrors];

export type UsersControllerGetUserResponses = {
    200: UserDto;
};

export type UsersControllerGetUserResponse = UsersControllerGetUserResponses[keyof UsersControllerGetUserResponses];

export type UsersControllerGetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersControllerGetAllUsersErrors = {
    401: ErrorDto;
};

export type UsersControllerGetAllUsersError = UsersControllerGetAllUsersErrors[keyof UsersControllerGetAllUsersErrors];

export type UsersControllerGetAllUsersResponses = {
    200: Array<unknown>;
};

export type UsersControllerGetAllUsersResponse = UsersControllerGetAllUsersResponses[keyof UsersControllerGetAllUsersResponses];

export type UsersControllerCreateData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersControllerCreateErrors = {
    400: ErrorDto;
};

export type UsersControllerCreateError = UsersControllerCreateErrors[keyof UsersControllerCreateErrors];

export type UsersControllerCreateResponses = {
    204: UserDto;
};

export type UsersControllerCreateResponse = UsersControllerCreateResponses[keyof UsersControllerCreateResponses];

export type UsersControllerSetProfilePicData = {
    body: SetProfilePicDto;
    path?: never;
    query?: never;
    url: '/users/setProfilePic';
};

export type UsersControllerSetProfilePicErrors = {
    400: ErrorDto;
    401: ErrorDto;
    404: ErrorDto;
};

export type UsersControllerSetProfilePicError = UsersControllerSetProfilePicErrors[keyof UsersControllerSetProfilePicErrors];

export type UsersControllerSetProfilePicResponses = {
    201: UserDto;
};

export type UsersControllerSetProfilePicResponse = UsersControllerSetProfilePicResponses[keyof UsersControllerSetProfilePicResponses];

export type UsersControllerSetUsernameData = {
    body: SetUsernameDto;
    path?: never;
    query?: never;
    url: '/users/setUsername';
};

export type UsersControllerSetUsernameErrors = {
    400: ErrorDto;
    401: ErrorDto;
    404: ErrorDto;
};

export type UsersControllerSetUsernameError = UsersControllerSetUsernameErrors[keyof UsersControllerSetUsernameErrors];

export type UsersControllerSetUsernameResponses = {
    201: UserDto;
};

export type UsersControllerSetUsernameResponse = UsersControllerSetUsernameResponses[keyof UsersControllerSetUsernameResponses];

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginErrors = {
    401: ErrorDto;
};

export type AuthControllerLoginError = AuthControllerLoginErrors[keyof AuthControllerLoginErrors];

export type AuthControllerLoginResponses = {
    201: {
        access_token?: string;
        refresh_token?: string;
    };
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerSignupData = {
    body: CreateUserDto;
    path?: never;
    query?: never;
    url: '/auth/signup';
};

export type AuthControllerSignupErrors = {
    400: ErrorDto;
    409: ErrorDto;
};

export type AuthControllerSignupError = AuthControllerSignupErrors[keyof AuthControllerSignupErrors];

export type AuthControllerSignupResponses = {
    201: unknown;
};

export type AuthControllerVerifyEmailData = {
    body: VerifyEmailDto;
    path?: never;
    query?: never;
    url: '/auth/verify-email';
};

export type AuthControllerVerifyEmailErrors = {
    400: ErrorDto;
    404: ErrorDto;
};

export type AuthControllerVerifyEmailError = AuthControllerVerifyEmailErrors[keyof AuthControllerVerifyEmailErrors];

export type AuthControllerVerifyEmailResponses = {
    201: {
        access_token?: string;
        refresh_token?: string;
    };
};

export type AuthControllerVerifyEmailResponse = AuthControllerVerifyEmailResponses[keyof AuthControllerVerifyEmailResponses];

export type AuthControllerForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type AuthControllerForgotPasswordErrors = {
    400: ErrorDto;
    404: ErrorDto;
};

export type AuthControllerForgotPasswordError = AuthControllerForgotPasswordErrors[keyof AuthControllerForgotPasswordErrors];

export type AuthControllerForgotPasswordResponses = {
    201: unknown;
};

export type AuthControllerConfirmPasswordResetData = {
    body: ConfirmPasswordResetDto;
    path?: never;
    query?: never;
    url: '/auth/confirmPasswordReset';
};

export type AuthControllerConfirmPasswordResetErrors = {
    400: ErrorDto;
    404: ErrorDto;
};

export type AuthControllerConfirmPasswordResetError = AuthControllerConfirmPasswordResetErrors[keyof AuthControllerConfirmPasswordResetErrors];

export type AuthControllerConfirmPasswordResetResponses = {
    201: unknown;
};

export type AuthControllerGoogleAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type AuthControllerGoogleAuthErrors = {
    401: ErrorDto;
};

export type AuthControllerGoogleAuthError = AuthControllerGoogleAuthErrors[keyof AuthControllerGoogleAuthErrors];

export type AuthControllerGoogleAuthResponses = {
    200: unknown;
};

export type AuthControllerGoogleAuthCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google/callback';
};

export type AuthControllerGoogleAuthCallbackErrors = {
    401: ErrorDto;
};

export type AuthControllerGoogleAuthCallbackError = AuthControllerGoogleAuthCallbackErrors[keyof AuthControllerGoogleAuthCallbackErrors];

export type AuthControllerGoogleAuthCallbackResponses = {
    200: unknown;
};

export type AuthControllerCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/currentUser';
};

export type AuthControllerCurrentUserErrors = {
    401: ErrorDto;
};

export type AuthControllerCurrentUserError = AuthControllerCurrentUserErrors[keyof AuthControllerCurrentUserErrors];

export type AuthControllerCurrentUserResponses = {
    200: UserDto;
};

export type AuthControllerCurrentUserResponse = AuthControllerCurrentUserResponses[keyof AuthControllerCurrentUserResponses];

export type AuthControllerRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshTokenErrors = {
    401: ErrorDto;
};

export type AuthControllerRefreshTokenError = AuthControllerRefreshTokenErrors[keyof AuthControllerRefreshTokenErrors];

export type AuthControllerRefreshTokenResponses = {
    201: UserDto;
};

export type AuthControllerRefreshTokenResponse = AuthControllerRefreshTokenResponses[keyof AuthControllerRefreshTokenResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthControllerLogoutErrors = {
    401: ErrorDto;
    404: ErrorDto;
};

export type AuthControllerLogoutError = AuthControllerLogoutErrors[keyof AuthControllerLogoutErrors];

export type AuthControllerLogoutResponses = {
    201: unknown;
};

export type UploadControllerGetPresignedUrlData = {
    body?: never;
    path?: never;
    query: {
        filename: string;
        fileType: string;
        folder: string;
    };
    url: '/upload/presign';
};

export type UploadControllerGetPresignedUrlResponses = {
    200: unknown;
};

export type UploadControllerDownloadData = {
    body?: never;
    path?: never;
    query: {
        key: string;
    };
    url: '/upload/access';
};

export type UploadControllerDownloadResponses = {
    200: unknown;
};

export type ListingsControllerCreateDraftData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/listings/draft';
};

export type ListingsControllerCreateDraftErrors = {
    401: ErrorDto;
};

export type ListingsControllerCreateDraftError = ListingsControllerCreateDraftErrors[keyof ListingsControllerCreateDraftErrors];

export type ListingsControllerCreateDraftResponses = {
    201: string;
};

export type ListingsControllerCreateDraftResponse = ListingsControllerCreateDraftResponses[keyof ListingsControllerCreateDraftResponses];

export type ListingsControllerCreateStep1Data = {
    body: CreateListingDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/listings/{id}/createStep1';
};

export type ListingsControllerCreateStep1Errors = {
    400: ErrorDto;
    403: ErrorDto;
    404: ErrorDto;
};

export type ListingsControllerCreateStep1Error = ListingsControllerCreateStep1Errors[keyof ListingsControllerCreateStep1Errors];

export type ListingsControllerCreateStep1Responses = {
    204: Listing;
};

export type ListingsControllerCreateStep1Response = ListingsControllerCreateStep1Responses[keyof ListingsControllerCreateStep1Responses];

export type ListingsControllerCreateStep2Data = {
    body: Step2ListingDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/listings/{id}/createStep2';
};

export type ListingsControllerCreateStep2Errors = {
    400: ErrorDto;
    403: ErrorDto;
    404: ErrorDto;
};

export type ListingsControllerCreateStep2Error = ListingsControllerCreateStep2Errors[keyof ListingsControllerCreateStep2Errors];

export type ListingsControllerCreateStep2Responses = {
    204: Listing;
};

export type ListingsControllerCreateStep2Response = ListingsControllerCreateStep2Responses[keyof ListingsControllerCreateStep2Responses];

export type ListingsControllerCreateStep3Data = {
    body: Step3ListingDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/listings/{id}/createStep3';
};

export type ListingsControllerCreateStep3Errors = {
    400: ErrorDto;
    403: ErrorDto;
    404: ErrorDto;
};

export type ListingsControllerCreateStep3Error = ListingsControllerCreateStep3Errors[keyof ListingsControllerCreateStep3Errors];

export type ListingsControllerCreateStep3Responses = {
    204: Listing;
};

export type ListingsControllerCreateStep3Response = ListingsControllerCreateStep3Responses[keyof ListingsControllerCreateStep3Responses];

export type ListingsControllerCreateStep4Data = {
    body: Step4ListingDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/listings/{id}/createStep4';
};

export type ListingsControllerCreateStep4Responses = {
    200: unknown;
};

export type ListingsControllerPublishData = {
    body: CreateListingDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/listings/{id}/publish';
};

export type ListingsControllerPublishErrors = {
    400: ErrorDto;
    403: ErrorDto;
    404: ErrorDto;
};

export type ListingsControllerPublishError = ListingsControllerPublishErrors[keyof ListingsControllerPublishErrors];

export type ListingsControllerPublishResponses = {
    204: Listing;
};

export type ListingsControllerPublishResponse = ListingsControllerPublishResponses[keyof ListingsControllerPublishResponses];

export type ListingsControllerDeleteListingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/listings/{id}';
};

export type ListingsControllerDeleteListingErrors = {
    400: ErrorDto;
    401: ErrorDto;
    403: ErrorDto;
    404: ErrorDto;
};

export type ListingsControllerDeleteListingError = ListingsControllerDeleteListingErrors[keyof ListingsControllerDeleteListingErrors];

export type ListingsControllerDeleteListingResponses = {
    204: Listing;
};

export type ListingsControllerDeleteListingResponse = ListingsControllerDeleteListingResponses[keyof ListingsControllerDeleteListingResponses];

export type ListingsControllerGetByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/listings/{id}';
};

export type ListingsControllerGetByIdErrors = {
    400: ErrorDto;
    401: ErrorDto;
    404: ErrorDto;
};

export type ListingsControllerGetByIdError = ListingsControllerGetByIdErrors[keyof ListingsControllerGetByIdErrors];

export type ListingsControllerGetByIdResponses = {
    200: Listing;
};

export type ListingsControllerGetByIdResponse = ListingsControllerGetByIdResponses[keyof ListingsControllerGetByIdResponses];

export type ListingsControllerMyListingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/listings/mine';
};

export type ListingsControllerMyListingsErrors = {
    400: ErrorDto;
    401: ErrorDto;
};

export type ListingsControllerMyListingsError = ListingsControllerMyListingsErrors[keyof ListingsControllerMyListingsErrors];

export type ListingsControllerMyListingsResponses = {
    200: Array<unknown>;
};

export type ListingsControllerMyListingsResponse = ListingsControllerMyListingsResponses[keyof ListingsControllerMyListingsResponses];

export type ListingsControllerGetListingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/listings/mine/{id}';
};

export type ListingsControllerGetListingErrors = {
    400: ErrorDto;
    403: ErrorDto;
    404: ErrorDto;
};

export type ListingsControllerGetListingError = ListingsControllerGetListingErrors[keyof ListingsControllerGetListingErrors];

export type ListingsControllerGetListingResponses = {
    200: Listing;
};

export type ListingsControllerGetListingResponse = ListingsControllerGetListingResponses[keyof ListingsControllerGetListingResponses];

export type ListingsControllerGetAllUnverifiedListingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/listings/allUnverified';
};

export type ListingsControllerGetAllUnverifiedListingsErrors = {
    400: ErrorDto;
    401: ErrorDto;
};

export type ListingsControllerGetAllUnverifiedListingsError = ListingsControllerGetAllUnverifiedListingsErrors[keyof ListingsControllerGetAllUnverifiedListingsErrors];

export type ListingsControllerGetAllUnverifiedListingsResponses = {
    200: Array<unknown>;
};

export type ListingsControllerGetAllUnverifiedListingsResponse = ListingsControllerGetAllUnverifiedListingsResponses[keyof ListingsControllerGetAllUnverifiedListingsResponses];

export type ListingsControllerVerifyListingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/listings/verify/{id}';
};

export type ListingsControllerVerifyListingErrors = {
    400: ErrorDto;
    401: ErrorDto;
    404: ErrorDto;
};

export type ListingsControllerVerifyListingError = ListingsControllerVerifyListingErrors[keyof ListingsControllerVerifyListingErrors];

export type ContactControllerContactData = {
    body: ContactDto;
    path?: never;
    query?: never;
    url: '/contact';
};

export type ContactControllerContactResponses = {
    201: unknown;
};

export type ApplicationControllerCreateApplicationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/application';
};

export type ApplicationControllerCreateApplicationResponses = {
    201: unknown;
};
